spring:
  application:
    name: catalogue-produit
  datasource:
    url: jdbc:postgresql://localhost:5432/produit
    username: iliasse
    password: mamamama
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format-sql: true

server:
  port: 8888
  servlet:
    context-path: /api
